import { NextResponse } from "next/server";

const images = [
  "https://qvbxbtfwzvyvwknkevcp.supabase.co/storage/v1/object/public/audiobook-demo/images/img-1.jpg",
  "https://qvbxbtfwzvyvwknkevcp.supabase.co/storage/v1/object/public/audiobook-demo/images/img-2.jpg",
];

const audios = [
  {
    url: "https://qvbxbtfwzvyvwknkevcp.supabase.co/storage/v1/object/public/audiobook-demo/audios/F16%20-%20The%20Grey%20Room%20_%20Golden%20Palms.mp3",
    duration: 196,
  },
  {
    url: "https://qvbxbtfwzvyvwknkevcp.supabase.co/storage/v1/object/public/audiobook-demo/audios/Down%20The%20Rabbit%20Hole%20-%20The%20Grey%20Room%20_%20Density%20&%20Time.mp3",
    duration: 184,
  },
];

export async function GET() {
  const audioBooks = {
    recommended: [
      {
        id: "rec-1",
        title: "The Silent Echo",
        author: "Sarah Mitchell",
        narrator: "James Anderson",
        thumbnail: images[0],
        audioUrl: audios[0].url,
        duration: audios[0].duration,
        description: "A thrilling mystery that keeps you on the edge",
      },
      {
        id: "rec-2",
        title: "Beyond the Horizon",
        author: "Michael Chen",
        narrator: "Emma Wilson",
        thumbnail: images[1],
        audioUrl: audios[1].url,
        duration: audios[1].duration,
        description: "An epic journey of self-discovery and adventure",
      },
      {
        id: "rec-3",
        title: "Whispers in the Dark",
        author: "Elena Rodriguez",
        narrator: "David Brown",
        thumbnail: images[0],
        audioUrl: audios[1].url,
        duration: audios[1].duration,
        description: "A haunting tale of love and redemption",
      },
      {
        id: "rec-4",
        title: "The Last Symphony",
        author: "Robert Blake",
        narrator: "Olivia Martinez",
        thumbnail: images[1],
        audioUrl: audios[0].url,
        duration: audios[0].duration,
        description: "Music, passion, and the pursuit of perfection",
      },
      {
        id: "rec-5",
        title: "Echoes of Tomorrow",
        author: "Jennifer Adams",
        narrator: "Chris Taylor",
        thumbnail: images[0],
        audioUrl: audios[0].url,
        duration: audios[0].duration,
        description: "A sci-fi adventure that challenges reality",
      },
      {
        id: "rec-6",
        title: "The Hidden Garden",
        author: "Amanda Foster",
        narrator: "Sophie Clark",
        thumbnail: images[1],
        audioUrl: audios[1].url,
        duration: audios[1].duration,
        description: "Secrets buried beneath the roses",
      },
      {
        id: "rec-7",
        title: "Midnight Chronicles",
        author: "Daniel Wright",
        narrator: "Rachel Green",
        thumbnail: images[1],
        audioUrl: audios[0].url,
        duration: audios[0].duration,
        description: "When darkness falls, heroes rise",
      },
      {
        id: "rec-8",
        title: "The Art of Letting Go",
        author: "Lisa Thompson",
        narrator: "Mark Johnson",
        thumbnail: images[0],
        audioUrl: audios[1].url,
        duration: audios[1].duration,
        description: "A journey through grief and healing",
      },
      {
        id: "rec-9",
        title: "Starlight Memories",
        author: "Kevin O'Brien",
        narrator: "Anna White",
        thumbnail: images[1],
        audioUrl: audios[0].url,
        duration: audios[0].duration,
        description: "Love stories written in the stars",
      },
      {
        id: "rec-10",
        title: "The Forgotten Path",
        author: "Maria Santos",
        narrator: "Thomas Lee",
        thumbnail: images[0],
        audioUrl: audios[1].url,
        duration: audios[1].duration,
        description: "An ancient mystery waiting to be solved",
      },
    ],
    newLaunches: [
      {
        id: "new-1",
        title: "Digital Dreams",
        author: "Alex Turner",
        narrator: "Mia Roberts",
        thumbnail: images[1],
        audioUrl: audios[0].url,
        duration: audios[0].duration,
        description: "The future of humanity in a virtual world",
      },
      {
        id: "new-2",
        title: "The Ocean's Secret",
        author: "Catherine Moore",
        narrator: "William Scott",
        thumbnail: images[0],
        audioUrl: audios[1].url,
        duration: audios[1].duration,
        description: "Mysteries from the depths of the sea",
      },
      {
        id: "new-3",
        title: "Shadows of the Past",
        author: "Gregory Hill",
        narrator: "Emily Davis",
        thumbnail: images[1],
        audioUrl: audios[1].url,
        duration: audios[1].duration,
        description: "History has a way of repeating itself",
      },
      {
        id: "new-4",
        title: "The Glass Tower",
        author: "Stephanie King",
        narrator: "Andrew Miller",
        thumbnail: images[0],
        audioUrl: audios[0].url,
        duration: audios[0].duration,
        description: "Corporate intrigue at its finest",
      },
      {
        id: "new-5",
        title: "Winter's Promise",
        author: "Patrick Snow",
        narrator: "Jessica Hart",
        thumbnail: images[0],
        audioUrl: audios[1].url,
        duration: audios[1].duration,
        description: "A heartwarming tale of hope and renewal",
      },
      {
        id: "new-6",
        title: "The Cipher Code",
        author: "Nathan Pierce",
        narrator: "Laura Bennett",
        thumbnail: images[1],
        audioUrl: audios[0].url,
        duration: audios[0].duration,
        description: "Crack the code, save the world",
      },
      {
        id: "new-7",
        title: "Dancing with Shadows",
        author: "Victoria Lane",
        narrator: "Ryan Cooper",
        thumbnail: images[0],
        audioUrl: audios[0].url,
        duration: audios[0].duration,
        description: "A dance between light and darkness",
      },
      {
        id: "new-8",
        title: "The Mountain's Call",
        author: "Brian Summit",
        narrator: "Karen Price",
        thumbnail: images[1],
        audioUrl: audios[1].url,
        duration: audios[1].duration,
        description: "Adventure awaits at the peak",
      },
      {
        id: "new-9",
        title: "Crimson Tide",
        author: "Diana Rivers",
        narrator: "Steven Hayes",
        thumbnail: images[1],
        audioUrl: audios[0].url,
        duration: audios[0].duration,
        description: "A thriller that will leave you breathless",
      },
      {
        id: "new-10",
        title: "The Writer's Muse",
        author: "Charlotte Brooks",
        narrator: "Michael Reed",
        thumbnail: images[0],
        audioUrl: audios[1].url,
        duration: audios[1].duration,
        description: "Where inspiration meets imagination",
      },
    ],
  };

  return NextResponse.json(audioBooks);
}
